COMP: Build against ITK 5 with ITK_LEGACY_REMOVE
The alias in itk::ImageIOBase has been deprecated.

To address:

In file included from /home/matt/src/ITK-Wasm/native/dicom-build/_deps/plastimatch_lib-src/src/base/plm_image_header.h:9,
                 from /home/matt/src/ITK-Wasm/native/dicom-build/_deps/plastimatch_lib-src/src/base/itk_resample.h:9,
                 from /home/matt/src/ITK-Wasm/native/dicom-build/_deps/plastimatch_lib-src/src/base/itk_resample.cxx:15:
/home/matt/src/ITK-Wasm/native/dicom-build/_deps/plastimatch_lib-src/src/base/itk_image.h:30:5: error: 'itk::ImageIOBase::IOPixelType' has not been declared
   30 |     itk::ImageIOBase::IOPixelType *pixel_type,
      |     ^~~

And many more.